### ISSUE TITLE
Possible CRIME-like attacks against arbitrary metadata

### ISSUE THREAD

**Issue by afrind** [ekinnear/draft-webtransport-http2#11]
If the WebTransport stream API allows sending completely arbitrary metadata, which is then compressed using the same compression context as other streams, it may introduce a CRIME-like attack in any case where an attacker can control the metadata on the WT streams and observe the size of packets transmitted on the network.

Perhaps this can be mitigated by specially name-spacing any arbitrary meta-data so it doesn't collide with Cookie and other sensitive HTTP headers that might be in the compression context.  Or at the very least, this deserves a mention in the Security Considerations.

**Comment by ekinnear** [comment]
Very good point! I suspect we should be on the lookout for other potential issues one could encounter when sharing an underlying HTTP/2 connection. That said, would you be allowed to share such a connection in situations where this would be an issue? (Not saying you wouldn't, just thinking the current discussion on the mailing list of how to select eligibility for sharing the underlying transport could be relevant here)

**Comment by afrind** [comment]
I think it must have been too early in the morning at the last IETF.  For CRIME to work, the compression scheme needs to be incremental (eg: if I guess part of your cookie then there are fewer bytes on the wire).  h2 WT would still use HPACK, so the attacker needs to completely guess the cookie to see an observable difference.  Closing for now.
